name: proypersical
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  provider: ^4.3.2+1
  flutter_advanced_networkimage:
  skeleton_loader:
  pull_to_refresh: ^1.6.1
  http: ^0.12.2
  expandable: ^4.1.4
  image_picker: ^0.6.7+22
  flutter_image_compress: ^0.7.0
  path_provider: ^1.6.28

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/

        
    
    
                                      